apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cronjob
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-cronjob
  template:
    metadata:
      labels:
        app: nginx-cronjob
    spec:
      containers:
      - name: nginx-cronjob
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/1 * * * *"  # Runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job-container
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cronjob-service
spec:
  type: NodePort
  selector:
    app: nginx-cronjob
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  # Assigning a specific port on the node, you can choose any available port
