apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-manual-lb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-manual-lb
  template:
    metadata:
      labels:
        app: nginx-manual-lb
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx-manual-lb
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-manual-lb-service
spec:
  selector:
    app: nginx-manual-lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

